# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fda16bb6a5fc22f103792796bf15881d3464f507a1e009e4066a7df4249c68b899e9d3c4428774a96cb6dafc250cfa740808f4bc781260293651bc635b1b60c7

test:
  secret_key_base: e8fcce92cd51dddc0a0d06c376170e506ddbf141c7eabd3fa1613a902f6ca8430dd54f6f37224e0227725ea3d9f0da1bb18da6db7e7c12795c398b32fb12de97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
